# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: DirSoft.ARPro
PackageVersion: 17.0.1.1058
InstallerType: exe
InstallerSwitches:
  Silent: /q
Installers:
- Architecture: x64
  InstallerUrl: https://www.dirigosoftware.com/dlfiles/ARSuite/arpro-setup.exe
  InstallerSha256: 298641EAC59C8EA32081E73A5840B3A5AAFBCEF185E36497003E8228EA7AC9EC
ManifestType: installer
ManifestVersion: 1.5.0
